NumPy (Numeric Python) – це бібліотека з відкритим кодом для Python, який надає базові
методи для маніпуляції з великими векторами, матрицями і багатовимірними масивами.
Бібліотека підтримує виконання загальних математичних і числових операцій за допомогою
пре-компільованих швидких функцій і методів. Вони реалізують функціонал, який можна
порівняти з функціоналом MatLab. SciPy (Scientific Python) розширює функціонал numpy
величезною колекцією корисних алгоритмів, таких як мінімізація, перетворення Фур’є,
регресія та інші прикладні математичні методи.

In [1]:
import numpy as np # класичний варіант імпорту бібліотеки NumPy

In [2]:
a = np.array([1, 4, 5, 8], float)
print(a)
print(type(a))

[1. 4. 5. 8.]
<class 'numpy.ndarray'>


In [3]:
b = np.array(range(10))
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
c = np.random.rand(4)
print(c)

[0.10678892 0.79250251 0.72729323 0.73316329]


In [5]:
print(a[a >= 5])
print(b[b%3 == 0])
print(a[a%3 == 0])

[5. 8.]
[0 3 6 9]
[]


In [6]:
d = np.arange(0, 100, 10)
print(d)
print(np.arange(5, dtype = float))
print(np.arange(1, 10, 0.5))

[ 0 10 20 30 40 50 60 70 80 90]
[0. 1. 2. 3. 4.]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [7]:
intervals = np.linspace(0,1,6)
print(intervals)

[0.  0.2 0.4 0.6 0.8 1. ]


In [8]:
print(d[[2,3,1,4,2]] == [20,30,20,40,50])

[ True  True False  True False]


In [9]:
print(d[3:])

[30 40 50 60 70 80 90]


In [10]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
print(a[b])

[2. 2. 4. 8. 6. 4.]


In [11]:
x = intervals.copy()
print(x)

[0.  0.2 0.4 0.6 0.8 1. ]


In [12]:
y = x.tolist()
print(y)
print(type(y))

[0.0, 0.2, 0.4, 0.6000000000000001, 0.8, 1.0]
<class 'list'>


In [13]:
matrix = np.array([[1, 2, 3], [4, 5, 6]], float)
print(matrix)

[[1. 2. 3.]
 [4. 5. 6.]]


In [14]:
row1 = matrix[0]
print(row1)

[1. 2. 3.]


In [15]:
column1 = matrix[:,0]
print(column1)

[1. 4.]


In [16]:
print(matrix.shape)

(2, 3)


In [17]:
print(type(matrix.shape))

<class 'tuple'>


In [18]:
print(matrix.dtype)

float64


In [19]:
print(matrix.ndim)

2


In [20]:
print(len(matrix))

2


In [21]:
print(2 in matrix)
print(10 in matrix)

True
False


In [22]:
print(np.ones((2,3), dtype=float))

[[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
print(np.zeros(7, dtype=int))

[0 0 0 0 0 0 0]


In [24]:
print(np.identity(4, dtype=float))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
print(np.eye(4, k=-1, dtype=float))

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [26]:
print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [27]:
a=np.eye(5,k=1,dtype=int)
b=np.eye(5,k=-1,dtype=int)
c=np.identity(5,dtype=int)
d=a+b+2*c
print(d)

[[2 1 0 0 0]
 [1 2 1 0 0]
 [0 1 2 1 0]
 [0 0 1 2 1]
 [0 0 0 1 2]]


In [28]:
a = np.array(range(10), float)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [29]:
a = a.reshape((2, 5))
print(a)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [30]:
a = a.flatten()
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [31]:
a = np.array([1, 2, 3])
print(a)
print(a.shape)

[1 2 3]
(3,)


In [32]:
a = a[:,np.newaxis]
print(a)
print(a.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [33]:
a = np.array([1, 2, 3])
a = a[np.newaxis,:]
print(a)
print(a.shape)

[[1 2 3]]
(1, 3)


In [34]:
b = np.random.rand(4,4)
print(b)

[[0.66200855 0.39241405 0.25136111 0.43855538]
 [0.71326962 0.60610022 0.77170425 0.73856062]
 [0.12252547 0.62749229 0.93737839 0.60019003]
 [0.5354218  0.01723673 0.50935407 0.58426015]]


In [35]:
b = b.transpose()
print(b)

[[0.66200855 0.71326962 0.12252547 0.5354218 ]
 [0.39241405 0.60610022 0.62749229 0.01723673]
 [0.25136111 0.77170425 0.93737839 0.50935407]
 [0.43855538 0.73856062 0.60019003 0.58426015]]


In [36]:
b = b.T
print(b)

[[0.66200855 0.39241405 0.25136111 0.43855538]
 [0.71326962 0.60610022 0.77170425 0.73856062]
 [0.12252547 0.62749229 0.93737839 0.60019003]
 [0.5354218  0.01723673 0.50935407 0.58426015]]


In [37]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.concatenate((a, b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [38]:
print(np.concatenate((a, b), axis = 0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [39]:
print(np.concatenate((a, b), axis = 1))

[[1 2 5 6]
 [3 4 7 8]]


In [40]:
a = np.array([[0, 2], [3, -1], [3, 5]], float)
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))

12.0
[6. 6.]
[2. 2. 8.]


In [41]:
print(a.mean())
print(a.max(axis=1))

2.0
[2. 3. 5.]


In [42]:
print(np.unique(a))

[-1.  0.  2.  3.  5.]


In [43]:
a = np.array([1, 3, 0], float)
print(np.where(a!=0, 1/a, a))

[1.         0.33333333 0.        ]


<ipython-input-43-21750109f625>:2: RuntimeWarning: divide by zero encountered in true_divide
  print(np.where(a!=0, 1/a, a))


In [44]:
print(np.where(a > 0, 3, 2))

[3 3 2]


In [45]:
x = np.arange(0, 100, 15)
print(x)
y = np.ones(7)
print(y)

[ 0 15 30 45 60 75 90]
[1. 1. 1. 1. 1. 1. 1.]


In [46]:
print(np.sin(x))

[ 0.          0.65028784 -0.98803162  0.85090352 -0.30481062 -0.38778164
  0.89399666]


In [47]:
np.sin(x, out = y)
print(y)

[ 0.          0.65028784 -0.98803162  0.85090352 -0.30481062 -0.38778164
  0.89399666]


In [50]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 0])
#print(a*b)
print(np.dot(a,b))

7


In [51]:
c = np.array([[1, 2], [3, 4]])
print(np.linalg.det(c))

-2.0000000000000004


In [52]:
print(np.linalg.inv(c))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [53]:
print(np.linalg.matrix_power(c, 3))

[[ 37  54]
 [ 81 118]]


In [54]:
print(np.linalg.solve(c, [2,3])) # Ax = b

[-1.   1.5]


In [55]:
poly = np.poly([-1, 2]) # многочлен за коренями
print(poly)

[ 1. -1. -2.]


In [56]:
roots = np.roots([1,5,6,3]) # корені многочлена
print(roots)

[-3.54681828+0.j         -0.72659086+0.56382109j -0.72659086-0.56382109j]
